name: champcash
version: 1.0.8+13
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  http: ^0.13.4
  intl: ^0.18.0
  path: ^1.8.3
  google_fonts: ^4.0.4
  rounded_loading_button: ^2.0.8
  shared_preferences: any
  #video_editor: ^3.0.0
  fluttertoast: any
  #syncfusion_flutter_datepicker: ^22.2.10
  #date_picker_timeline: ^1.2.3
  flutter_easyloading: ^3.0.5
  #flutter_otp_text_field: ^1.1.0+2
  camera: ^0.10.5+2
  cached_video_preview: ^1.0.0
  video_thumbnail: any
  fancy_shimmer_image: ^2.0.2
  ionicons: ^0.2.2
  clipboard: ^0.1.3
  image_picker: ^1.0.2
  video_player: ^2.6.0
  chewie: ^1.5.0
  #argear_flutter_plugin: 0.0.3
  cached_video_player: ^2.0.4
  firebase_messaging: ^14.6.7
  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_database: ^10.2.3
  firebase_storage: ^11.2.7
  firebase_core_platform_interface: ^4.8.0
  logger: ^2.0.1
  path_provider: ^2.0.11
  otp_text_field: ^1.1.3
  video_compress: ^3.1.2
  #scrollable_positioned_list: ^0.3.5
  flutter_countdown_timer: ^4.1.0
  #preload_page_view: ^0.2.0
  transparent_image: ^2.0.1
  share: 2.0.4
  velocity_x: ^4.1.0
  audioplayers: ^4.1.0
  firebase_crashlytics: ^3.3.6
  just_audio: ^0.9.34
  #glob: ^2.1.2
  file_picker: ^5.2.10
  dio: ^5.2.1+1
  cached_network_image: ^3.2.3
  permission_handler: ^10.3.0
  #change_app_package_name: ^1.1.0
  #get_storage: ^2.1.1
  deepar_flutter: ^0.0.4
  ffmpeg_kit_flutter: ^5.1.0-LTS
  media_info: ^0.12.0+2
  flutter_local_notifications: 13.0.0
  easy_audio_trimmer: ^1.0.1
  video_trimmer: ^2.1.0
  #video_trimmer: ^3.0.0-LTS
  #video_editor: ^2.2.0




  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
    - assets/drawable/
    - assets/gift/
    - assets/filters/
    - images/
    - assets/fPreview/

  uses-material-design: true

